import 'package:dropdown_textfield/dropdown_textfield.dart';

List<DropDownValueModel> cropNames = const [
  DropDownValueModel(name: 'maize', value: 'maize'),
  DropDownValueModel(name: 'rice', value: 'rice'),
  DropDownValueModel(name: 'chickpea', value: 'chickpea'),
  DropDownValueModel(name: 'kidneybeans', value: 'kidneybeans'),
  DropDownValueModel(name: 'pidgeonpeas', value: 'pidgeonpeas'),
  DropDownValueModel(name: 'mothbean', value: 'mothbean'),
  DropDownValueModel(name: 'mungbean', value: 'mungbean'),
  DropDownValueModel(name: 'blackgram', value: 'blackgram'),
  DropDownValueModel(name: 'lentil', value: 'lentil'),
  DropDownValueModel(name: 'pomegranate', value: 'pomegranate'),
  DropDownValueModel(name: 'banana', value: 'banana'),
  DropDownValueModel(name: 'mango', value: 'mango'),
  DropDownValueModel(name: 'grapes', value: 'grapes'),
  DropDownValueModel(name: 'watermelon', value: 'watermelon'),
  DropDownValueModel(name: 'muskmelon', value: 'muskmelon'),
  DropDownValueModel(name: 'apple', value: 'apple'),
  DropDownValueModel(name: 'orange', value: 'orange'),
  DropDownValueModel(name: 'papaya', value: 'papaya'),
  DropDownValueModel(name: 'millet', value: 'millet'),
  DropDownValueModel(name: 'sorghum', value: 'sorghum'),
  DropDownValueModel(name: 'yam', value: 'yam'),
  DropDownValueModel(name: 'groundnut', value: 'groundnut'),
  DropDownValueModel(name: 'sweetpotato', value: 'sweetpotato'),
  DropDownValueModel(name: 'cassava', value: 'cassava'),
  DropDownValueModel(name: 'soybean', value: 'soybean'),
  DropDownValueModel(name: 'bean', value: 'bean'),
  DropDownValueModel(name: 'cucumber', value: 'cucumber'),
  DropDownValueModel(name: 'pepper', value: 'pepper'),
  DropDownValueModel(name: 'tomato', value: 'tomato'),
  DropDownValueModel(name: 'mucuna', value: 'mucuna'),
  DropDownValueModel(name: 'cowpea', value: 'cowpea'),
  DropDownValueModel(name: 'coffee', value: 'coffee'),
  DropDownValueModel(name: 'coconut', value: 'coconut'),
  DropDownValueModel(name: 'cotton', value: 'cotton'),
  DropDownValueModel(name: 'jute', value: 'jute'),
  DropDownValueModel(name: 'other', value: 'other'),
];

List<DropDownValueModel> family = [
  DropDownValueModel(name: 'legume', value: 'legume'),
  DropDownValueModel(name: 'grasses', value: 'grasses'),
  DropDownValueModel(name: 'punicaceae', value: 'punicaceae'),
  DropDownValueModel(name: 'musaceae', value: 'musaceae'),
  DropDownValueModel(name: 'anacardiaceae', value: 'anacardiaceae'),
  DropDownValueModel(name: 'vitaceae', value: 'vitaceae'),
  DropDownValueModel(name: 'cucurbitaceae', value: 'cucurbitaceae'),
  DropDownValueModel(name: 'rosaceae', value: 'rosaceae'),
  DropDownValueModel(name: 'rutaceae', value: 'rutaceae'),
  DropDownValueModel(name: 'caricaceae', value: 'caricaceae'),
  DropDownValueModel(name: 'arecaceae', value: 'arecaceae'),
  DropDownValueModel(name: 'malvaceae', value: 'malvaceae'),
  DropDownValueModel(name: 'rubiaceae', value: 'rubiaceae'),
  DropDownValueModel(name: 'discoreaceae', value: 'discoreaceae'),
  DropDownValueModel(name: 'convolvulaceae', value: 'convolvulaceae'),
  DropDownValueModel(name: 'euphorbiaceae', value: 'euphorbiaceae'),
  DropDownValueModel(name: 'solanaceae', value: 'solanaceae'),
  DropDownValueModel(name: 'other', value: 'other'),
];

